<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BookingSystemWeb.Application\BookingSystemWeb.Application.csproj" />
      <ProjectReference Include="..\BookingSystemWeb.Domain\BookingSystemWeb.Domain.csproj" />
    </ItemGroup>

</Project>
